### ISSUE TITLE
筛选结果默认不显示，筛选后再展示

### ISSUE THREAD

**Issue by baixin513** [fit2cloud-ui/fit2cloud-ui-plus#2]
期望表格上面的筛选结果默认不显示如下图。
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/52996290/185080335-3a6f32aa-75ff-437b-b208-4d30f1c1875d.png">

在输入筛选条件查询后在展示筛选结果和筛选条件。
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/52996290/185074614-ccd70d17-6e8d-497f-822f-922556724ab4.png">

**当前显示如下图：**
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/52996290/185075484-3a46fa54-2685-4b85-b788-edf364ecacec.png">

**Comment by q4speed** [comment]
下个版本改进这个问题。
