### ISSUE TITLE
文本搜索框支持按指定字段搜索

### ISSUE THREAD

**Issue by baixin513** [fit2cloud-ui/fit2cloud-ui-plus#3]
文本搜索框支持按指定字段搜索，如下图：
<img width="422" alt="image" src="https://user-images.githubusercontent.com/52996290/185080055-0474148f-7b1f-433f-91da-3e328364b056.png">

**Comment by q4speed** [comment]
Elment-plus里有这个功能
![image](https://user-images.githubusercontent.com/21072886/185085272-d7d16c24-a8b7-4d58-a569-03f5812988f8.png)

**Comment by baixin513** [comment]
是filter组件里面的搜索框前面增加一个下拉列表，下拉选项为table表格里面的文本字段， 满足用户选择某个字段去做筛选。

**Comment by q4speed** [comment]
已发布
